### ISSUE TITLE
Cannot find module 'fs/promises'

### ISSUE THREAD

**Issue by rajasegar-c** [TylorS/snowpack-plugin-optimize#1]
Getting the below error while running build using `yarn build`

```
Require stack:
yarn run v1.22.4
$ snowpack build

Error: Cannot find module 'fs/promises'
- /Users/rajasegarchandran/www/glimmerx/glimmer-7guis/node_modules/snowpack-plugin-optimize/lib/index.js
- /Users/rajasegarchandran/www/glimmerx/glimmer-7guis/node_modules/snowpack/lib/config.js
- /Users/rajasegarchandran/www/glimmerx/glimmer-7guis/node_modules/snowpack/lib/build/build-pipeline.js
- /Users/rajasegarchandran/www/glimmerx/glimmer-7guis/node_modules/snowpack/lib/commands/build.js
- /Users/rajasegarchandran/www/glimmerx/glimmer-7guis/node_modules/snowpack/lib/index.js
- /Users/rajasegarchandran/www/glimmerx/glimmer-7guis/node_modules/snowpack/index.bin.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:966:15)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/Users/rajasegarchandran/www/glimmerx/glimmer-7guis/node_modules/snowpack-plugin-optimize/lib/index.js:5:20)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
```

**Comment by TylorS** [comment]
Hey @rajasegar-c , thanks for opening up an issue. What version of node are you using?
